/**
 * PreOne Enterprise Error Codes Registry
 * Canonical, stable error codes across all modules and infrastructure layers.
 */

export const ErrorCodes = {
  // Authentication & Authorization (401, 403)
  AUTH_REQUIRED: 'AUTH_001',
  AUTH_INVALID_SESSION: 'AUTH_002',
  AUTH_EXPIRED_SESSION: 'AUTH_003',
  AUTH_INVALID_CREDENTIALS: 'AUTH_004',
  AUTH_ACCOUNT_LOCKED: 'AUTH_005',

  PERMISSION_DENIED: 'PERMISSION_001',
  PERMISSION_OWNER_ESCALATION: 'PERMISSION_002',
  PERMISSION_BRANCH_RESTRICTED: 'PERMISSION_003',
  PERMISSION_ROLE_ESCALATION: 'PERMISSION_004',
  PERMISSION_CROSS_TENANT: 'PERMISSION_005',

  // Resource Not Found (404)
  NOT_FOUND_RESOURCE: 'NOT_FOUND_001',
  NOT_FOUND_USER: 'NOT_FOUND_USER_001',
  NOT_FOUND_STAFF: 'NOT_FOUND_STAFF_001',
  NOT_FOUND_GUARDIAN: 'NOT_FOUND_GUARDIAN_001',
  NOT_FOUND_STUDENT: 'NOT_FOUND_STUDENT_001',
  NOT_FOUND_CLASSROOM: 'NOT_FOUND_CLASSROOM_001',
  NOT_FOUND_BRANCH: 'NOT_FOUND_BRANCH_001',
  NOT_FOUND_INVOICE: 'NOT_FOUND_INVOICE_001',
  NOT_FOUND_TEMPLATE: 'NOT_FOUND_TEMPLATE_001',
  NOT_FOUND_SESSION: 'NOT_FOUND_SESSION_001',
  NOT_FOUND_ROUTE: 'NOT_FOUND_ROUTE_001',

  // Conflict / Duplicate Records (409)
  CONFLICT_DUPLICATE_RECORD: 'CONFLICT_001',
  CONFLICT_DUPLICATE_EMAIL: 'CONFLICT_EMAIL_001',
  CONFLICT_DUPLICATE_PHONE: 'CONFLICT_PHONE_001',
  CONFLICT_EMPLOYEE_CODE: 'CONFLICT_EMPLOYEE_CODE_001',
  CONFLICT_ADMISSION_NO: 'CONFLICT_ADMISSION_NO_001',
  CONFLICT_STUDENT_GUARDIAN: 'CONFLICT_STUDENT_GUARDIAN_001',
  CONFLICT_STATE: 'CONFLICT_STATE_001',

  // Validation Failures (400 / 422)
  VALIDATION_GENERAL: 'VALIDATION_001',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED_001',
  VALIDATION_EMAIL: 'VALIDATION_EMAIL_001',
  VALIDATION_PHONE: 'VALIDATION_PHONE_001',
  VALIDATION_FORMAT: 'VALIDATION_FORMAT_001',
  VALIDATION_DATE: 'VALIDATION_DATE_001',
  VALIDATION_AGE_ELIGIBILITY: 'VALIDATION_AGE_ELIGIBILITY_001',
  VALIDATION_CSV_ROW: 'VALIDATION_CSV_ROW_001',

  // Business Operational Rules (422)
  BUSINESS_RULE_VIOLATION: 'BUSINESS_001',
  BUSINESS_PARENT_LIMIT_EXCEEDED: 'BUSINESS_PARENT_LIMIT_001',
  BUSINESS_CLASSROOM_FULL: 'BUSINESS_CLASSROOM_FULL_001',
  BUSINESS_FEE_ALREADY_PAID: 'BUSINESS_FEE_ALREADY_PAID_001',
  BUSINESS_FEE_PLAN_MISSING: 'BUSINESS_FEE_PLAN_MISSING_001',
  BUSINESS_ACADEMIC_YEAR_CLOSED: 'BUSINESS_ACADEMIC_YEAR_CLOSED_001',
  BUSINESS_ATTENDANCE_ALREADY_MARKED: 'BUSINESS_ATTENDANCE_ALREADY_MARKED_001',
  BUSINESS_PICKUP_UNAUTHORIZED: 'BUSINESS_PICKUP_UNAUTHORIZED_001',
  BUSINESS_SETUP_DEPENDENCY_MISSING: 'BUSINESS_SETUP_DEPENDENCY_001',
  BUSINESS_INSUFFICIENT_STOCK: 'BUSINESS_INSUFFICIENT_STOCK_001',
  BUSINESS_OVERRIDE_REASON_REQUIRED: 'BUSINESS_OVERRIDE_REASON_001',

  // Rate Limiting (429)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_001',

  // Audit Observability
  AUDIT_WRITE_FAILED: 'AUDIT_WRITE_FAILED',

  // Developer / System Faults (500)
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_001',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_002',
  SYSTEM_DATABASE_ERROR: 'SYSTEM_DB_001',
  SYSTEM_THIRD_PARTY_ERROR: 'SYSTEM_EXTERNAL_001',
  SYSTEM_CSV_PROCESSING_ERROR: 'SYSTEM_CSV_001',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes] | string
