/**
 * PreOne — Starter Document Presets
 * Production-ready templates matching real preschool requirements.
 */

import { DocumentType, TemplateDefinition, PAGE_DIMENSIONS } from './types'

export interface TemplatePresetMeta {
  type: DocumentType
  name: string
  description: string
  thumbnailIcon: string
  definition: TemplateDefinition
}

export const TEMPLATE_PRESETS: Record<DocumentType, TemplatePresetMeta> = {
  // ── 1. STUDENT ID CARD ──
  STUDENT_ID_CARD: {
    type: 'STUDENT_ID_CARD',
    name: 'Official Student Smart Card',
    description: 'Standard CR80 portrait badge with photo, emergency contact & gate QR.',
    thumbnailIcon: 'Contact',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'STUDENT_ID_CARD',
      pageSize: 'ID_CARD_PORTRAIT',
      orientation: 'portrait',
      widthMm: 54,
      heightMm: 85.6,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 3, right: 3, bottom: 3, left: 3 },
      elements: [
        // Top Header Accent Bar
        {
          id: 'card-header-bg',
          type: 'shape',
          name: 'Header Banner',
          x: 0,
          y: 0,
          width: 54,
          height: 18,
          zIndex: 1,
          content: '',
          styles: {
            backgroundColor: '#4C1D95',
            borderRadius: 0,
          },
        },
        // School Name in Header
        {
          id: 'card-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 2,
          y: 3,
          width: 50,
          height: 8,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 8,
            fontWeight: 'bold',
            color: '#FFFFFF',
            textAlign: 'center',
            textTransform: 'uppercase',
          },
        },
        // School Subtitle
        {
          id: 'card-header-sub',
          type: 'text',
          name: 'Badge Subtitle',
          x: 2,
          y: 11,
          width: 50,
          height: 5,
          zIndex: 2,
          content: 'STUDENT IDENTITY CARD',
          styles: {
            fontSize: 5,
            fontWeight: '600',
            color: '#DDD6FE',
            textAlign: 'center',
            letterSpacing: 1,
          },
        },
        // Student Photo Box
        {
          id: 'card-photo',
          type: 'photo',
          name: 'Student Photo',
          x: 16,
          y: 20,
          width: 22,
          height: 25,
          zIndex: 3,
          content: '{{student.photoUrl}}',
          fieldBinding: 'student.photoUrl',
          styles: {
            backgroundColor: '#F1F5F9',
            borderColor: '#CBD5E1',
            borderWidth: 1,
            borderRadius: 4,
          },
        },
        // Student Full Name
        {
          id: 'card-student-name',
          type: 'bound-text',
          name: 'Student Name',
          x: 2,
          y: 46,
          width: 50,
          height: 6,
          zIndex: 3,
          content: '{{student.fullName}}',
          fieldBinding: 'student.fullName',
          styles: {
            fontSize: 9,
            fontWeight: 'bold',
            color: '#0F172A',
            textAlign: 'center',
          },
        },
        // Admission No & Program
        {
          id: 'card-details-line1',
          type: 'bound-text',
          name: 'Class & Program',
          x: 4,
          y: 52,
          width: 46,
          height: 5,
          zIndex: 3,
          content: 'Class: {{classroom.name}}',
          fieldBinding: 'classroom.name',
          styles: {
            fontSize: 6,
            fontWeight: '500',
            color: '#475569',
            textAlign: 'center',
          },
        },
        {
          id: 'card-details-line2',
          type: 'bound-text',
          name: 'Adm No & Blood Group',
          x: 4,
          y: 57,
          width: 46,
          height: 5,
          zIndex: 3,
          content: 'Adm: {{student.admissionNumber}} | Blood: {{student.bloodGroup}}',
          styles: {
            fontSize: 5.5,
            fontWeight: '600',
            color: '#334155',
            textAlign: 'center',
          },
        },
        // Emergency Phone
        {
          id: 'card-emergency',
          type: 'bound-text',
          name: 'Emergency Phone',
          x: 4,
          y: 62,
          width: 46,
          height: 5,
          zIndex: 3,
          content: 'Emergency: {{student.emergencyPhone}}',
          fieldBinding: 'student.emergencyPhone',
          styles: {
            fontSize: 5.5,
            fontWeight: 'bold',
            color: '#DC2626',
            textAlign: 'center',
          },
        },
        // QR Code for Gate Scanner
        {
          id: 'card-qr',
          type: 'qrcode',
          name: 'Gate Access QR',
          x: 21,
          y: 68,
          width: 12,
          height: 12,
          zIndex: 3,
          content: 'https://preone.school/verify/{{student.admissionNumber}}',
          fieldBinding: 'student.admissionNumber',
          styles: {
            backgroundColor: '#FFFFFF',
            borderWidth: 0,
          },
        },
        // Bottom Footer Strip
        {
          id: 'card-footer-strip',
          type: 'shape',
          name: 'Footer Accent',
          x: 0,
          y: 83.6,
          width: 54,
          height: 2,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#7C3AED',
          },
        },
      ],
    },
  },

  // ── 2. STAFF ID CARD ──
  STAFF_ID_CARD: {
    type: 'STAFF_ID_CARD',
    name: 'Faculty & Educator Credential',
    description: 'Portrait CR80 staff credential with department and emergency contact.',
    thumbnailIcon: 'IdCard',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'STAFF_ID_CARD',
      pageSize: 'ID_CARD_PORTRAIT',
      orientation: 'portrait',
      widthMm: 54,
      heightMm: 85.6,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 3, right: 3, bottom: 3, left: 3 },
      elements: [
        {
          id: 'staff-header-bg',
          type: 'shape',
          name: 'Header Banner',
          x: 0,
          y: 0,
          width: 54,
          height: 17,
          zIndex: 1,
          content: '',
          styles: {
            backgroundColor: '#1E293B',
          },
        },
        {
          id: 'staff-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 2,
          y: 3,
          width: 50,
          height: 7,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 7.5,
            fontWeight: 'bold',
            color: '#FFFFFF',
            textAlign: 'center',
            textTransform: 'uppercase',
          },
        },
        {
          id: 'staff-title',
          type: 'text',
          name: 'Faculty Credential',
          x: 2,
          y: 10,
          width: 50,
          height: 5,
          zIndex: 2,
          content: 'STAFF & FACULTY CREDENTIAL',
          styles: {
            fontSize: 5,
            fontWeight: '600',
            color: '#38BDF8',
            textAlign: 'center',
            letterSpacing: 0.5,
          },
        },
        {
          id: 'staff-photo',
          type: 'photo',
          name: 'Staff Photo',
          x: 16,
          y: 19,
          width: 22,
          height: 25,
          zIndex: 3,
          content: '{{staff.photoUrl}}',
          fieldBinding: 'staff.photoUrl',
          styles: {
            backgroundColor: '#F8FAFC',
            borderColor: '#CBD5E1',
            borderWidth: 1,
            borderRadius: 4,
          },
        },
        {
          id: 'staff-name',
          type: 'bound-text',
          name: 'Staff Name',
          x: 2,
          y: 45,
          width: 50,
          height: 6,
          zIndex: 3,
          content: '{{staff.fullName}}',
          fieldBinding: 'staff.fullName',
          styles: {
            fontSize: 8.5,
            fontWeight: 'bold',
            color: '#0F172A',
            textAlign: 'center',
          },
        },
        {
          id: 'staff-desig',
          type: 'bound-text',
          name: 'Designation',
          x: 2,
          y: 51,
          width: 50,
          height: 5,
          zIndex: 3,
          content: '{{staff.designation}}',
          fieldBinding: 'staff.designation',
          styles: {
            fontSize: 6,
            fontWeight: '600',
            color: '#2563EB',
            textAlign: 'center',
          },
        },
        {
          id: 'staff-dept',
          type: 'bound-text',
          name: 'Dept & Code',
          x: 2,
          y: 56,
          width: 50,
          height: 5,
          zIndex: 3,
          content: 'Dept: {{staff.department}} | ID: {{staff.employeeCode}}',
          fieldBinding: 'staff.department',
          styles: {
            fontSize: 5.5,
            fontWeight: '500',
            color: '#64748B',
            textAlign: 'center',
          },
        },
        {
          id: 'staff-phone',
          type: 'bound-text',
          name: 'Contact Phone',
          x: 2,
          y: 61,
          width: 50,
          height: 5,
          zIndex: 3,
          content: 'Phone: {{staff.phone}}',
          fieldBinding: 'staff.phone',
          styles: {
            fontSize: 5.5,
            fontWeight: '500',
            color: '#334155',
            textAlign: 'center',
          },
        },
        {
          id: 'staff-barcode',
          type: 'barcode',
          name: 'Staff Barcode',
          x: 10,
          y: 68,
          width: 34,
          height: 12,
          zIndex: 3,
          content: '{{staff.employeeCode}}',
          fieldBinding: 'staff.employeeCode',
          styles: {},
        },
        {
          id: 'staff-footer-accent',
          type: 'shape',
          name: 'Footer Accent',
          x: 0,
          y: 83.6,
          width: 54,
          height: 2,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#2563EB',
          },
        },
      ],
    },
  },

  // ── 3. FEE RECEIPT ──
  FEE_RECEIPT: {
    type: 'FEE_RECEIPT',
    name: 'Executive Fee Receipt (A5 Landscape)',
    description: 'Clean financial receipt with fee breakdown table, QR code & signature line.',
    thumbnailIcon: 'Receipt',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'FEE_RECEIPT',
      pageSize: 'RECEIPT_HALF_A4',
      orientation: 'landscape',
      widthMm: 210,
      heightMm: 148,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 8, right: 8, bottom: 8, left: 8 },
      elements: [
        // Outer Border
        {
          id: 'rec-border',
          type: 'shape',
          name: 'Document Border',
          x: 5,
          y: 5,
          width: 200,
          height: 138,
          zIndex: 1,
          content: '',
          styles: {
            backgroundColor: '#FFFFFF',
            borderColor: '#E2E8F0',
            borderWidth: 1,
            borderRadius: 4,
          },
        },
        // Header Left - School Info
        {
          id: 'rec-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 10,
          y: 8,
          width: 120,
          height: 7,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 13,
            fontWeight: 'bold',
            color: '#1E1B4B',
          },
        },
        {
          id: 'rec-school-address',
          type: 'bound-text',
          name: 'School Address',
          x: 10,
          y: 16,
          width: 120,
          height: 5,
          zIndex: 2,
          content: '{{school.address}}, {{school.city}}',
          styles: {
            fontSize: 7,
            color: '#64748B',
          },
        },
        {
          id: 'rec-school-contact',
          type: 'bound-text',
          name: 'School Contact',
          x: 10,
          y: 21,
          width: 120,
          height: 5,
          zIndex: 2,
          content: 'Phone: {{school.phone}} | Email: {{school.email}}',
          styles: {
            fontSize: 7,
            color: '#64748B',
          },
        },
        // Header Right - Receipt Badge & Voucher No
        {
          id: 'rec-badge',
          type: 'text',
          name: 'Receipt Title',
          x: 140,
          y: 8,
          width: 60,
          height: 7,
          zIndex: 2,
          content: 'FEE PAYMENT RECEIPT',
          styles: {
            fontSize: 10,
            fontWeight: 'bold',
            color: '#047857',
            textAlign: 'right',
            letterSpacing: 0.5,
          },
        },
        {
          id: 'rec-no',
          type: 'bound-text',
          name: 'Receipt Number',
          x: 140,
          y: 16,
          width: 60,
          height: 5,
          zIndex: 2,
          content: 'Receipt No: {{finance.receiptNumber}}',
          fieldBinding: 'finance.receiptNumber',
          styles: {
            fontSize: 8,
            fontWeight: '600',
            color: '#334155',
            textAlign: 'right',
          },
        },
        {
          id: 'rec-date',
          type: 'bound-text',
          name: 'Payment Date',
          x: 140,
          y: 21,
          width: 60,
          height: 5,
          zIndex: 2,
          content: 'Date: {{finance.paymentDate}}',
          fieldBinding: 'finance.paymentDate',
          styles: {
            fontSize: 7.5,
            color: '#64748B',
            textAlign: 'right',
          },
        },
        // Divider
        {
          id: 'rec-hr1',
          type: 'shape',
          name: 'Divider Line 1',
          x: 10,
          y: 27,
          width: 190,
          height: 0.5,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#CBD5E1',
          },
        },
        // Student Info Grid
        {
          id: 'rec-student-meta',
          type: 'bound-text',
          name: 'Student Info Block',
          x: 10,
          y: 29,
          width: 120,
          height: 12,
          zIndex: 2,
          content: 'Student: {{student.fullName}} (Adm: {{student.admissionNumber}})\nClass / Program: {{classroom.name}} - {{classroom.program}}\nParent / Guardian: {{guardian.primaryName}} (Ph: {{guardian.phone}})',
          styles: {
            fontSize: 7.5,
            color: '#1E293B',
            lineHeight: 1.4,
          },
        },
        {
          id: 'rec-invoice-meta',
          type: 'bound-text',
          name: 'Invoice Info Block',
          x: 135,
          y: 29,
          width: 65,
          height: 12,
          zIndex: 2,
          content: 'Invoice Ref: {{finance.invoiceNumber}}\nPayment Mode: {{finance.paymentMethod}}\nTransaction ID: {{finance.transactionRef}}',
          styles: {
            fontSize: 7.5,
            color: '#475569',
            lineHeight: 1.4,
            textAlign: 'right',
          },
        },
        // Dynamic Line Items Table
        {
          id: 'rec-table',
          type: 'table',
          name: 'Fee Line Items Table',
          x: 10,
          y: 44,
          width: 190,
          height: 48,
          zIndex: 2,
          content: '',
          styles: {
            tableColumns: [
              { key: 'item', label: 'Particulars / Fee Head', widthPercent: 55, align: 'left' },
              { key: 'term', label: 'Term / Period', widthPercent: 20, align: 'left' },
              { key: 'amount', label: 'Amount (₹)', widthPercent: 25, align: 'right' },
            ],
          },
        },
        // Total & Amount in words
        {
          id: 'rec-in-words',
          type: 'bound-text',
          name: 'Amount in Words',
          x: 10,
          y: 96,
          width: 130,
          height: 8,
          zIndex: 2,
          content: 'In Words: {{finance.amountInWords}}',
          fieldBinding: 'finance.amountInWords',
          styles: {
            fontSize: 7.5,
            fontWeight: '600',
            color: '#1E293B',
          },
        },
        {
          id: 'rec-total-box',
          type: 'bound-text',
          name: 'Total Paid Summary',
          x: 145,
          y: 94,
          width: 55,
          height: 12,
          zIndex: 2,
          content: 'Total Paid: {{finance.paidAmount}}',
          fieldBinding: 'finance.paidAmount',
          styles: {
            fontSize: 10,
            fontWeight: 'bold',
            color: '#047857',
            textAlign: 'right',
          },
        },
        // Footer & Signatures
        {
          id: 'rec-hr2',
          type: 'shape',
          name: 'Divider Line 2',
          x: 10,
          y: 108,
          width: 190,
          height: 0.5,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#E2E8F0',
          },
        },
        {
          id: 'rec-terms',
          type: 'text',
          name: 'Terms & Conditions',
          x: 10,
          y: 111,
          width: 120,
          height: 14,
          zIndex: 2,
          content: '• Fees once paid are non-refundable & non-transferable.\n• This is a system-generated electronic receipt valid under Indian IT Act 2000.',
          styles: {
            fontSize: 6,
            color: '#94A3B8',
            lineHeight: 1.3,
          },
        },
        {
          id: 'rec-sig-line',
          type: 'signature',
          name: 'Authorized Signatory',
          x: 145,
          y: 111,
          width: 55,
          height: 18,
          zIndex: 2,
          content: 'Authorized Signatory\nAccounts Department',
          styles: {
            fontSize: 7,
            color: '#475569',
            textAlign: 'center',
          },
        },
      ],
    },
  },

  // ── 4. CERTIFICATE OF MERIT ──
  CERTIFICATE: {
    type: 'CERTIFICATE',
    name: 'Excellence & Completion Certificate (A4 Landscape)',
    description: 'Gold-accented certificate of achievement with dual signatures & seal.',
    thumbnailIcon: 'Award',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'CERTIFICATE',
      pageSize: 'CERTIFICATE_A4',
      orientation: 'landscape',
      widthMm: 297,
      heightMm: 210,
      backgroundColor: '#FAF5FF',
      marginsMm: { top: 12, right: 12, bottom: 12, left: 12 },
      elements: [
        // Ornate Border Frame
        {
          id: 'cert-outer-border',
          type: 'shape',
          name: 'Outer Gold Frame',
          x: 10,
          y: 10,
          width: 277,
          height: 190,
          zIndex: 1,
          content: '',
          styles: {
            backgroundColor: '#FFFFFF',
            borderColor: '#D97706',
            borderWidth: 2,
            borderRadius: 8,
          },
        },
        {
          id: 'cert-inner-border',
          type: 'shape',
          name: 'Inner Accent Frame',
          x: 13,
          y: 13,
          width: 271,
          height: 184,
          zIndex: 2,
          content: '',
          styles: {
            borderColor: '#FDE68A',
            borderWidth: 1,
            borderRadius: 6,
          },
        },
        // School Name
        {
          id: 'cert-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 20,
          y: 22,
          width: 257,
          height: 10,
          zIndex: 3,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 16,
            fontWeight: 'bold',
            color: '#6B21A8',
            textAlign: 'center',
            letterSpacing: 1.5,
          },
        },
        {
          id: 'cert-sub-title',
          type: 'text',
          name: 'Presents Title',
          x: 20,
          y: 33,
          width: 257,
          height: 6,
          zIndex: 3,
          content: 'FOUNDATION EARLY YEARS PROGRAMME',
          styles: {
            fontSize: 8,
            fontWeight: '600',
            color: '#92400E',
            textAlign: 'center',
            letterSpacing: 2,
          },
        },
        // Main Title
        {
          id: 'cert-heading',
          type: 'text',
          name: 'Certificate Header',
          x: 20,
          y: 44,
          width: 257,
          height: 16,
          zIndex: 3,
          content: 'Certificate of Achievement',
          styles: {
            fontSize: 26,
            fontWeight: 'bold',
            fontFamily: 'Georgia, serif',
            color: '#1E1B4B',
            textAlign: 'center',
          },
        },
        {
          id: 'cert-prose-1',
          type: 'text',
          name: 'Award Statement',
          x: 20,
          y: 64,
          width: 257,
          height: 7,
          zIndex: 3,
          content: 'This certificate is proudly awarded to',
          styles: {
            fontSize: 10,
            color: '#64748B',
            textAlign: 'center',
          },
        },
        // Student Name Large
        {
          id: 'cert-student-name',
          type: 'bound-text',
          name: 'Recipient Name',
          x: 20,
          y: 74,
          width: 257,
          height: 16,
          zIndex: 3,
          content: '{{student.fullName}}',
          fieldBinding: 'student.fullName',
          styles: {
            fontSize: 24,
            fontWeight: 'bold',
            fontFamily: 'Georgia, serif',
            color: '#7C3AED',
            textAlign: 'center',
          },
        },
        // Description
        {
          id: 'cert-description',
          type: 'text',
          name: 'Commendation Text',
          x: 35,
          y: 93,
          width: 227,
          height: 18,
          zIndex: 3,
          content: 'for demonstrating exceptional curiosity, creative expression, and outstanding social development in Early Years Foundation during the academic session {{school.academicYear}}.',
          styles: {
            fontSize: 9.5,
            color: '#334155',
            textAlign: 'center',
            lineHeight: 1.5,
          },
        },
        // Date & Signatures
        {
          id: 'cert-date',
          type: 'bound-text',
          name: 'Certificate Date',
          x: 35,
          y: 135,
          width: 60,
          height: 15,
          zIndex: 3,
          content: 'Date of Award\n{{system.currentDate}}',
          fieldBinding: 'system.currentDate',
          styles: {
            fontSize: 8.5,
            color: '#475569',
            textAlign: 'center',
          },
        },
        {
          id: 'cert-teacher-sig',
          type: 'signature',
          name: 'Teacher Signature',
          x: 118,
          y: 135,
          width: 60,
          height: 25,
          zIndex: 3,
          content: 'Lead Educator\nEarly Years Faculty',
          styles: {
            fontSize: 8.5,
            color: '#475569',
            textAlign: 'center',
          },
        },
        {
          id: 'cert-principal-sig',
          type: 'signature',
          name: 'Principal Signature',
          x: 202,
          y: 135,
          width: 60,
          height: 25,
          zIndex: 3,
          content: '{{school.principalName}}\nHead of School',
          fieldBinding: 'school.principalName',
          styles: {
            fontSize: 8.5,
            color: '#475569',
            textAlign: 'center',
          },
        },
      ],
    },
  },

  // ── 5. ADMISSION FORM ──
  ADMISSION_FORM: {
    type: 'ADMISSION_FORM',
    name: 'Preschool Admission Application (A4 Portrait)',
    description: 'Comprehensive registration form with parent info, medical notes & photo box.',
    thumbnailIcon: 'FileSpreadsheet',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'ADMISSION_FORM',
      pageSize: 'A4_PORTRAIT',
      orientation: 'portrait',
      widthMm: 210,
      heightMm: 297,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 10, right: 10, bottom: 10, left: 10 },
      elements: [
        {
          id: 'adm-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 10,
          y: 10,
          width: 140,
          height: 8,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 14,
            fontWeight: 'bold',
            color: '#1E1B4B',
          },
        },
        {
          id: 'adm-address',
          type: 'bound-text',
          name: 'School Address',
          x: 10,
          y: 18,
          width: 140,
          height: 6,
          zIndex: 2,
          content: '{{school.address}}, {{school.city}} | Ph: {{school.phone}}',
          styles: {
            fontSize: 7.5,
            color: '#64748B',
          },
        },
        {
          id: 'adm-photo-box',
          type: 'photo',
          name: 'Affix Photo Box',
          x: 165,
          y: 10,
          width: 35,
          height: 42,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#F8FAFC',
            borderColor: '#94A3B8',
            borderWidth: 1,
            borderRadius: 2,
          },
        },
        {
          id: 'adm-title-banner',
          type: 'text',
          name: 'Form Title',
          x: 10,
          y: 28,
          width: 140,
          height: 8,
          zIndex: 2,
          content: 'STUDENT ADMISSION ENROLMENT FORM',
          styles: {
            fontSize: 11,
            fontWeight: 'bold',
            color: '#4C1D95',
          },
        },
        {
          id: 'adm-sec-1',
          type: 'text',
          name: 'Section 1 Header',
          x: 10,
          y: 56,
          width: 190,
          height: 6,
          zIndex: 2,
          content: '1. CHILD DETAILS',
          styles: {
            fontSize: 9,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#4C1D95',
          },
        },
        {
          id: 'adm-child-fields',
          type: 'bound-text',
          name: 'Child Fields Block',
          x: 10,
          y: 64,
          width: 190,
          height: 25,
          zIndex: 2,
          content: 'Full Name: {{student.fullName}}\nDate of Birth: {{student.dob}}    | Gender: {{student.gender}}    | Blood Group: {{student.bloodGroup}}\nApplied Program: {{classroom.program}}    | Academic Session: {{school.academicYear}}',
          styles: {
            fontSize: 8.5,
            color: '#1E293B',
            lineHeight: 1.6,
          },
        },
        {
          id: 'adm-sec-2',
          type: 'text',
          name: 'Section 2 Header',
          x: 10,
          y: 95,
          width: 190,
          height: 6,
          zIndex: 2,
          content: '2. PARENT / GUARDIAN INFORMATION',
          styles: {
            fontSize: 9,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#4C1D95',
          },
        },
        {
          id: 'adm-guardian-fields',
          type: 'bound-text',
          name: 'Guardian Fields Block',
          x: 10,
          y: 103,
          width: 190,
          height: 25,
          zIndex: 2,
          content: 'Primary Contact: {{guardian.primaryName}} ({{guardian.relationship}})\nMobile Phone: {{guardian.phone}}    | Email: {{guardian.email}}\nResidential Address: {{student.address}}',
          styles: {
            fontSize: 8.5,
            color: '#1E293B',
            lineHeight: 1.6,
          },
        },
        {
          id: 'adm-sec-3',
          type: 'text',
          name: 'Section 3 Header',
          x: 10,
          y: 135,
          width: 190,
          height: 6,
          zIndex: 2,
          content: '3. DECLARATION & UNDERTAKING',
          styles: {
            fontSize: 9,
            fontWeight: 'bold',
            color: '#FFFFFF',
            backgroundColor: '#4C1D95',
          },
        },
        {
          id: 'adm-decl-text',
          type: 'text',
          name: 'Declaration Prose',
          x: 10,
          y: 143,
          width: 190,
          height: 20,
          zIndex: 2,
          content: 'I hereby declare that all particulars stated in this application are true and correct to the best of my knowledge. I agree to abide by the rules, health and safety regulations, and fee policies of {{school.name}}.',
          styles: {
            fontSize: 8,
            color: '#475569',
            lineHeight: 1.5,
          },
        },
        {
          id: 'adm-sig-parent',
          type: 'signature',
          name: 'Parent Signature',
          x: 10,
          y: 180,
          width: 70,
          height: 20,
          zIndex: 2,
          content: 'Signature of Parent / Guardian\nDate: ________________',
          styles: {
            fontSize: 8,
            color: '#334155',
            textAlign: 'center',
          },
        },
        {
          id: 'adm-sig-office',
          type: 'signature',
          name: 'Office Approval',
          x: 130,
          y: 180,
          width: 70,
          height: 20,
          zIndex: 2,
          content: 'Verified & Approved by Principal\nEnrolment Status: PROVISIONAL',
          styles: {
            fontSize: 8,
            color: '#334155',
            textAlign: 'center',
          },
        },
      ],
    },
  },

  // ── 6. REPORT CARD ──
  REPORT_CARD: {
    type: 'REPORT_CARD',
    name: 'Holistic Progress Evaluation (A4 Portrait)',
    description: 'Early years developmental assessment with milestone criteria & teacher notes.',
    thumbnailIcon: 'GraduationCap',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'REPORT_CARD',
      pageSize: 'A4_PORTRAIT',
      orientation: 'portrait',
      widthMm: 210,
      heightMm: 297,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 8, right: 8, bottom: 8, left: 8 },
      elements: [
        {
          id: 'rep-header-bg',
          type: 'shape',
          name: 'Header Accent Box',
          x: 8,
          y: 8,
          width: 194,
          height: 22,
          zIndex: 1,
          content: '',
          styles: {
            backgroundColor: '#4338CA',
            borderRadius: 4,
          },
        },
        {
          id: 'rep-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 12,
          y: 11,
          width: 186,
          height: 8,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 14,
            fontWeight: 'bold',
            color: '#FFFFFF',
            textAlign: 'center',
          },
        },
        {
          id: 'rep-title',
          type: 'text',
          name: 'Card Title',
          x: 12,
          y: 20,
          width: 186,
          height: 6,
          zIndex: 2,
          content: 'EARLY YEARS HOLISTIC PROGRESS REPORT',
          styles: {
            fontSize: 8,
            fontWeight: '600',
            color: '#C7D2FE',
            textAlign: 'center',
            letterSpacing: 1.5,
          },
        },
        // Profile Summary
        {
          id: 'rep-student-profile',
          type: 'bound-text',
          name: 'Student Profile Card',
          x: 8,
          y: 33,
          width: 194,
          height: 16,
          zIndex: 2,
          content: 'Child Name: {{student.fullName}}    | Adm No: {{student.admissionNumber}}\nProgram: {{classroom.program}} ({{classroom.name}})    | Term: Term 1 Evaluation\nHomeroom Educator: {{classroom.primaryTeacher}}',
          styles: {
            fontSize: 8.5,
            color: '#1E293B',
            lineHeight: 1.5,
            backgroundColor: '#F8FAFC',
            borderColor: '#E2E8F0',
            borderWidth: 1,
            borderRadius: 4,
          },
        },
        // Milestone Ratings Table
        {
          id: 'rep-table',
          type: 'table',
          name: 'Developmental Domains Table',
          x: 8,
          y: 54,
          width: 194,
          height: 120,
          zIndex: 2,
          content: '',
          styles: {
            tableColumns: [
              { key: 'domain', label: 'Developmental Learning Domain', widthPercent: 50, align: 'left' },
              { key: 'milestone', label: 'Key Observable Milestone', widthPercent: 30, align: 'left' },
              { key: 'rating', label: 'Proficiency Level', widthPercent: 20, align: 'center' },
            ],
          },
        },
        // Teacher Remarks Box
        {
          id: 'rep-remarks-label',
          type: 'text',
          name: 'Educator Observations Title',
          x: 8,
          y: 180,
          width: 194,
          height: 5,
          zIndex: 2,
          content: 'TEACHER REMARKS & HOLISTIC OBSERVATIONS',
          styles: {
            fontSize: 8,
            fontWeight: 'bold',
            color: '#374151',
          },
        },
        {
          id: 'rep-remarks-box',
          type: 'text',
          name: 'Remarks Content Box',
          x: 8,
          y: 186,
          width: 194,
          height: 30,
          zIndex: 2,
          content: 'Aarav is an enthusiastic, expressive participant during circle time and interactive phonics sessions. He demonstrates strong fine motor dexterity with building blocks and cooperative play with peers. Shows remarkable curiosity in outdoor sensory exploration.',
          styles: {
            fontSize: 8.5,
            color: '#334155',
            backgroundColor: '#F9FAFB',
            borderColor: '#D1D5DB',
            borderWidth: 1,
            borderRadius: 4,
            lineHeight: 1.5,
          },
        },
        // Signatures
        {
          id: 'rep-sig-teacher',
          type: 'signature',
          name: 'Lead Teacher Signature',
          x: 15,
          y: 230,
          width: 60,
          height: 20,
          zIndex: 2,
          content: 'Lead Educator Signature\n{{classroom.primaryTeacher}}',
          styles: {
            fontSize: 8,
            color: '#475569',
            textAlign: 'center',
          },
        },
        {
          id: 'rep-sig-principal',
          type: 'signature',
          name: 'Principal Signature & Seal',
          x: 135,
          y: 230,
          width: 60,
          height: 20,
          zIndex: 2,
          content: 'Head of School\n{{school.principalName}}',
          styles: {
            fontSize: 8,
            color: '#475569',
            textAlign: 'center',
          },
        },
      ],
    },
  },

  // ── 7. GENERAL LETTER / CIRCULAR ──
  GENERAL_LETTER: {
    type: 'GENERAL_LETTER',
    name: 'Official Institutional Circular / Bonafide (A4 Portrait)',
    description: 'Formal letterhead with school header, date, recipient and signature blocks.',
    thumbnailIcon: 'FileText',
    definition: {
      version: 1,
      status: 'PUBLISHED',
      documentType: 'GENERAL_LETTER',
      pageSize: 'A4_PORTRAIT',
      orientation: 'portrait',
      widthMm: 210,
      heightMm: 297,
      backgroundColor: '#FFFFFF',
      marginsMm: { top: 15, right: 15, bottom: 15, left: 15 },
      elements: [
        {
          id: 'let-school-name',
          type: 'bound-text',
          name: 'School Name',
          x: 15,
          y: 15,
          width: 180,
          height: 9,
          zIndex: 2,
          content: '{{school.name}}',
          fieldBinding: 'school.name',
          styles: {
            fontSize: 16,
            fontWeight: 'bold',
            color: '#1E1B4B',
            textAlign: 'center',
          },
        },
        {
          id: 'let-school-meta',
          type: 'bound-text',
          name: 'School Address Line',
          x: 15,
          y: 25,
          width: 180,
          height: 6,
          zIndex: 2,
          content: '{{school.address}}, {{school.city}} | Phone: {{school.phone}} | Email: {{school.email}}',
          styles: {
            fontSize: 7.5,
            color: '#64748B',
            textAlign: 'center',
          },
        },
        {
          id: 'let-hr1',
          type: 'shape',
          name: 'Header Rule',
          x: 15,
          y: 33,
          width: 180,
          height: 1,
          zIndex: 2,
          content: '',
          styles: {
            backgroundColor: '#7C3AED',
          },
        },
        {
          id: 'let-date',
          type: 'bound-text',
          name: 'Date Line',
          x: 15,
          y: 40,
          width: 80,
          height: 6,
          zIndex: 2,
          content: 'Date: {{system.currentDate}}',
          fieldBinding: 'system.currentDate',
          styles: {
            fontSize: 8.5,
            fontWeight: '600',
            color: '#334155',
          },
        },
        {
          id: 'let-subject',
          type: 'text',
          name: 'Subject Line',
          x: 15,
          y: 52,
          width: 180,
          height: 8,
          zIndex: 2,
          content: 'TO WHOMSOEVER IT MAY CONCERN — BONAFIDE CERTIFICATE',
          styles: {
            fontSize: 10,
            fontWeight: 'bold',
            color: '#0F172A',
          },
        },
        {
          id: 'let-body',
          type: 'bound-text',
          name: 'Letter Body Prose',
          x: 15,
          y: 64,
          width: 180,
          height: 50,
          zIndex: 2,
          content: 'This is to certify that {{student.fullName}}, son/daughter of {{guardian.primaryName}}, bearing Admission Number {{student.admissionNumber}}, is a bonafide student of {{school.name}} enrolled in {{classroom.name}} ({{classroom.program}}) for the academic year {{school.academicYear}}.\n\nAccording to our official school records, their date of birth is {{student.dob}}.\n\nThis certificate is issued upon the request of the parent/guardian for official administrative verification.',
          styles: {
            fontSize: 9.5,
            color: '#1E293B',
            lineHeight: 1.7,
          },
        },
        {
          id: 'let-sig',
          type: 'signature',
          name: 'Principal Signature',
          x: 120,
          y: 130,
          width: 75,
          height: 25,
          zIndex: 2,
          content: '{{school.principalName}}\nPrincipal & Head of School\n{{school.name}}',
          styles: {
            fontSize: 8.5,
            color: '#334155',
            textAlign: 'center',
          },
        },
      ],
    },
  },
}
